spring:
  session:
    storage-type: redis
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org:
      springframework:
        web: DEBUG
        cache: DEBUG
